### ISSUE TITLE
Add Philly outline as a mask

### ISSUE THREAD

**Issue by danrademacher** [stamen/philly-civiccommons#1]
Here's the recommended file: https://raw.githubusercontent.com/CityOfPhiladelphia/CityPlanning-geodata/master/Philadelphia_City_Limits/Philadelphia_City_Limits.geojson

As we talked about Sean, this would be good as a window with everything else screened back.

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/7234218/768e1394-e753-11e4-82bc-3e0f16e806f6.png)
